title: "UE-Sim"
description: "UE-Sim is an end-to-end Ultra Ethernet network simulation platform for AI and HPC workloads."
url: "https://kaima2022.github.io"
baseurl: "/UE-Sim"
repository: "kaima2022/UE-Sim"
lang: "en-US"
timezone: "Asia/Shanghai"

theme: jekyll-theme-primer

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
